version: "3.8"
services:
  web_client:
    build: ./amcat4client
    container_name: amcat4cient
    # restart: unless-stopped
    networks:
      - amcat-net
    ports:
      - 80:5000 # [local port]:[container port]
    depends_on:
      - "api"
  api:
    build: ./amcat4
    container_name: amcat4
    # restart: unless-stopped
    networks:
      - amcat-net
    depends_on:
      - "db"
    environment:
      amcat4_elastic_host: elastic7:9200
    command: ["./wait-for-it.sh", "elastic7:9200", "--", "amcat4", "run"]
  db:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.7
    container_name: elastic7
    # restart: unless-stopped
    networks:
      - amcat-net
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    # your database should have a folder on the host machine to permanently store data
    # run: `mkdir -p ~/.elasticsearch/database && sudo chown -R 1000:1000 ~/.elasticsearch/database`
    # to make it accessible for docker. Then uncomment the lines below (feel free to use different directory)
    volumes: 
      - ~/.elasticsearch/database:/usr/share/elasticsearch/data

networks:
  amcat-net:
