name: nightlies

on:
  schedule:
    - cron: "30 0 * * *"
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push ngincat
        uses: docker/build-push-action@v3
        with:
          context: ./ngincat
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ccsamsterdam/ngincat:nightlies
      - name: Build and push nextcat
        uses: docker/build-push-action@v3
        with:
          context: ./nextcat
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ccsamsterdam/nextcat:nightlies
      - name: Build and push amcat4
        uses: docker/build-push-action@v3
        with:
          context: ./amcat4
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ccsamsterdam/amcat4:nightlies
